openapi: 3.0.1
info:
  title: API Base de Datos JSON
  description: API para consultar una base de datos en JSON.
  version: '1.0'
servers:
  - url: https://me-api-f475.onrender.com
paths:
  /leer_base:
    get:
      operationId: leerBase
      summary: Obtener toda la base de datos.
      description: Retorna el contenido completo de la base de datos en formato JSON.
      responses:
        '200':
          description: Respuesta exitosa, base de datos en JSON.
          content:
            application/json:
              schema:
                type: object
                description: Base de datos en formato JSON.
