openapi: 3.1.0
info:
  title: API Base de Datos de Ejercicios
  description: API que entrega una base de datos de ejercicios en formato JSON.
  version: '1.0'
servers:
  - url: https://me-api-f475.onrender.com
paths:
  /leer_base:
    get:
      operationId: leerBase
      summary: Obtener todos los ejercicios.
      description: Retorna un JSON con la lista de ejercicios almacenados en la base de datos.
      responses:
        '200':
          description: Respuesta exitosa.
          content:
            application/json:
              schema:
                type: object
                properties:
                  ejercicios:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        profesor:
                          type: string
                        fecha:
                          type: string
                        fuente:
                          type: string
                        keywords:
                          type: array
                          items:
                            type: string
                        formato:
                          type: string
                        enunciado:
                          type: string
                        preguntas:
                          type: object
                        img:
                          type: array
                          items:
                            type: string
                required:
                  - ejercicios
